name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descargar el c贸digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Iniciar sesi贸n en el Container Registry de GitHub
      # Usamos el token interno de GitHub para autenticaci贸n
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # Paso 3: Construir y subir la imagen Docker al registro
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Nombramos la imagen con el formato de GitHub Packages
          tags: ghcr.io/diegobalaguer/s0501-advancedspringwithwebflux:latest

      # Paso 4: Desplegar la imagen en Render
      # Esta acci贸n se encarga de llamar a la API de Render
      - name: Trigger Render deploy
        run: |
            curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" -H "Content-Type: application/json" "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
